[tool.poetry]
name = "gridappsd-cim-profile"
version = "0.6.0"
description = "CIM models used within gridappsd."
authors = ["C. Allwardt <3979063+craig8@users.noreply.github.com>"]
packages = [
    { include = "cimlab" }
]

[tool.poetry.dependencies]
python = "^3.8"
xsdata = "^22.5"
SPARQLWrapper = "^2.0.0"

gridappsd-python = { git = "https://github.com/GRIDAPPSD/gridappsd-python.git", branch = "cim-profile", optional = true }

[tool.poetry.extras]
gridappsd = ["gridappsd-python"]

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
xsdata = {extras = ["cli"], version = "^22.2"}
xsdata-plantuml = "^21.4"
graphviz = "^0.19.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
